fix: improve responsiveness and add lazy loading to the popup contents
promotedai/react-introspection pull request #5
Opened 2022-09-28 22:02 UTC by prm-eric-schneider

Adds some box math to better position the popup on screen resize (no more disappearing over the edge of the screen, etc).

2022-09-30 22:06 UTC, danbosnichill approved these changes

2022-09-30 22:06 UTC, danbosnichill commented on src/Cell/CellPopup.tsx
> +      if (popupContainerRef.current) {
I don't know React well to see if there are corner cases around this.

Is there a way for `popupContainerRef.current` to not be set at this point?  Does it matter if we leak unobserving on the resizeObserver?

2022-09-30 22:06 UTC, danbosnichill commented on src/Cell/PromotedIntrospectionCell.tsx
> +import React, { Suspense, useRef } from 'react'
Is it safe to use Suspense?  I know it was in experimental mode for a long time.  I'd guess it's okay to use it but I don't know.

2022-09-30 22:06 UTC, danbosnichill commented on src/Cell/PromotedIntrospectionCell.tsx
> +    body.style.overflow = contextMenuOpen && introspectionEndpoint ? 'hidden' : 'initial'
What's the chance this clobbers important style properties that customers have set?  I want to make sure we don't cause a weird bug for them.

2022-10-03 16:14 UTC, prm-eric-schneider commented on src/Cell/CellPopup.tsx
> +      if (popupContainerRef.current) {
> Is there a way for popupContainerRef.current to not be set at this point?
It's strange that it wouldn't be set, but it *might* be possible.  The `useEffect` callback short-circuits on line 99, but by the time React invokes the callback returned from line 104 it's possible it could have been unset (not sure why this would happen).  I don't think I would have included this check if `TypeScript` wasn't yelling at me about `popupContainerRef.current` possibly being `null`.  Probably better to be safe about it.

2022-10-03 16:25 UTC, prm-eric-schneider commented on src/Cell/PromotedIntrospectionCell.tsx
> +import React, { Suspense, useRef } from 'react'
It looks like it came out officially in React 16.6, and we're asking for at least React 16.8 from the consumer.  I think it should be safe.  Good idea to check on it.

2022-10-03 16:27 UTC, prm-eric-schneider commented on src/Cell/PromotedIntrospectionCell.tsx
> +    body.style.overflow = contextMenuOpen && introspectionEndpoint ? 'hidden' : 'initial'
I think most modal libraries do the same sort of thing in order to keep the page from scrolling behind the modal.  But that said you may be right that it isn't worth the risk of interfering.  It shouldn't be too much of a problem to allow them to scroll the page, and if it is we can add a prop for it later or something.  I'll yank this out for now.

2022-10-03 18:23 UTC, prm-eric-schneider commented on src/Cell/CellPopup.tsx
> +export const CellPopup = ({ triggerContainerRef, introspectionData, handleClose }: CellPopupArgs) => {
`triggerContainerRef` will contain a reference to the search item DOM element which will be used by the popup to position itself.

If you're referring to `CellPopup` then yeah, this won't be fetched until React tries to render it

2022-10-05 18:16 UTC, prm-eric-schneider commented on src/Cell/StatsPanel.tsx
> +      tooltip: 'Price',
We're going to need better content for these tooltips.  This is just placeholder.

2022-10-05 19:18 UTC, danbosnichill commented on src/Cell/CellPopup.tsx
> +export const CellPopup = ({ triggerContainerRef, introspectionData, handleClose }: CellPopupArgs) => {
Cool, thanks.  I didn't know this framework.  Sometimes "Popup" describes the inner contents, sometimes the wrapper too.

2022-10-05 19:19 UTC, danbosnichill commented on src/Cell/PromotedIntrospectionCell.tsx
> +    body.style.overflow = contextMenuOpen && introspectionEndpoint ? 'hidden' : 'initial'
I don't have a good solution.  You could stash the original value.  However, if anything collides with it, there will be bugs.  We could make it disabling it an optional prop.

2022-10-05 19:26 UTC, danbosnichill requested changes

2022-10-05 19:26 UTC, danbosnichill commented on src/Cell/StatsPanel.tsx
> +      label: 'p(Purchase)',
I'm okay with these for now.  We can iterate on it later.

I think `p(Purchase)` might confuse people since this is actually `p(Purchase | Click)` and some people might think it's `p(Purchase | Impression)`.

We use "Navigates" more frequently in other parts of our product.

2022-10-05 19:26 UTC, danbosnichill commented on src/Cell/StatsPanel.tsx
> +      value: queryRelevance,
Some of these values are wrong.  I'm assuming they're placeholders.

2022-10-05 19:26 UTC, danbosnichill commented on src/Cell/StatsPanel.tsx
> +      label: 'CTR',
Do you know if we exposing both the probability and the recent performance (I assume these)?

2022-10-05 19:26 UTC, danbosnichill commented on src/Cell/StatsPanel.tsx
> +      label: 'Price',
I don't know why price is in this panel.  They already have price in the UI.

2022-10-06 13:17 UTC, prm-eric-schneider commented on src/Cell/StatsPanel.tsx
> +      value: queryRelevance,
Yeah, just placeholders for now.  I'll update this in the follow-up PR that includes some changes based on my latest understanding about how we're going to integrate with clients.

2022-10-06 13:38 UTC, prm-eric-schneider commented on src/Cell/StatsPanel.tsx
> +      label: 'Price',
When @yunapotamus  is back, I think it would be great to huddle on these things.  I'll also share the fields that we're currently getting back from the introspection endpoint so that we can align on what we want to show vs what we have available.

2022-10-06 13:46 UTC, prm-eric-schneider commented on src/Cell/StatsPanel.tsx
> +      label: 'p(Purchase)',
So with what's in this PR, should `p(Click)` be updated to `p(Navigates)` and `p(Purchase)` updated to `p(Purchase | Navigates)` ?

2022-10-08 15:45 UTC, danbosnichill commented on src/Cell/StatsPanel.tsx
> +      label: 'p(Purchase)',
Yes for `p(Navigate)`.

As for `p(Purchase | Navigates)` vs `p(Purchase | Impression)` vs something else, what's the field or feature ID that is being pulled from?

2022-10-08 15:45 UTC, danbosnichill approved these changes

2022-10-08 15:46 UTC, merged